all:
	g++ --std=c++11 server.cpp -o server
	g++ --std=c++11 client.cpp -o client
server:
	g++ --std=c++11 server.cpp -o server
run_server: server
	./server.out 5001
client:
	g++ --std=c++11 client.cpp -o client
